version: 0.1

phases:
  install:
    commands:
      - npm install

  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/main.css
    - images/*
    - dist/bundle.js
